### Задание 1
Создайте numpy array с элементами от числа N до 0   (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [8]:
# Условие задачи можно понять по-разному:
# 'С элементами от числа N' имеется ввиду включая это число или,
# что N - это кол-во чисел, которое должно полчится в array? 
# сбивает с верного пути пример с array, в котором N не включается в массив

In [9]:
N = 10

In [10]:
np.arange(N, -1, step=-1) #вкл N: первое число 10, и всего в array 11 чисел  

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
np.arange(N-1, -1, step=-1) #N не включаем, всего в array 10 чисел  

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [12]:
def diagonal_matrix(N):
    d = int(round(N ** 0.5, 0))
    N = d ** 2
    x = np.arange(N).reshape((d, d))
    x = np.diag(np.diag(x))
    return x

In [13]:
diagonal_matrix(int(input()))

23


array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

### Задание 3  
Решите систему уравнений:  
4x + 2y + z = 4  
x + 3y = 12  
5y + 4z = -3  

In [14]:
from numpy import linalg as LA

In [15]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [16]:
LA.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [17]:
np.allclose(np.dot(a, LA.solve(a, b)), b)

True

### Задание 4
Найти похожего пользователя (посчитать косинусовое расстояние)

In [42]:
# имеет ли смысл использовать в реальной задачи количественные признаки, вместо бинарных?
# к примеру, из клиента можно сделать вектор типа [0,1,1,0,1,0,0,1], где 1 - это наличие какого-то признака
# в данный задаче, как я понял, используется количественные признаки, к примеру количество транзакций = 4
# К сожалению в лекции не было сказано, что если в векторе используются количественные признаки - вектор лучше 
# нормализовать (привести к единичной длине), чтобы минимизировать ошибку. 
# Например, если вектор содержит кол-во транзакций = 5 и оборот = 30000000

customer = [[0, 2, 3, 5, 0, 0, 3],
            [1, 0, 4, 0, 9, 3, 4],
            [2, 3, 0, 0, 2, 4, 2],
            [3, 0, 4, 2, 2, 0, 5],
            [4, 1, 3, 2, 5, 6, 4],
            [5, 0, 4, 0, 0, 0, 2]]

In [53]:
def cosine(client, customer):
    user_distance = 0
    user = 0
    length_client = np.linalg.norm(client)
    for i in range(len(customer)):
        length_customer_i = np.linalg.norm(customer[i])
        cos_distance = np.dot(client, customer[i]) / (length_client*length_customer_i)
        if cos_distance > user_distance:
            user_distance = cos_distance
            user = customer[i][0]
    #return user_distance
    print(f'Нового пользователя id {client[0]} можно отнести в группу с пользователем {user}, расстояние между пользователями составляет {user_distance}')

In [54]:
client = input(f'Введите вектор для клиента: {len(customer[1])} цифр через пробел: ')
client = np.array(list(map(int, client.split())))
cosine(client, customer)

Введите вектор для клиента: 7 цифр через пробел: 6 4 4 5 3 3 4
Нового пользователя id 6 можно отнести в группу с пользователем 4, расстояние между пользователями составляет 0.8492615172803017
